baseURL = "https://arthurmco.github.io/blog/"
languageCode = "pt-br"
title = "Blog do Arthur M."
description = "Meu diário de coisas interessantes"
theme = "terminal"
disqusShortname = "https-arthurmco-github-io-blog"

[params]
  fullWidthTheme = false
  centerTheme = true
  themeColor = "red"
  enableGitInfo = true

[params.logo]
  logoText = "Blog do Arthur M."