baseURL = "https://arthurmco.github.io/blog/"
languageCode = "pt-br"
title = "Blog do Arthur M."
theme = "terminal"

[params]
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"
  enableGitInfo = true

[params.logo]
  logoText = "Blog do Arthur M."