baseURL = "https://arthurmco.github.io/blog/"
languageCode = "pt-br"
title = "Blog do Arthur M."
subtitle = "Meu diário de coisas interessantes"
theme = "terminal"
disqusShortname = "https-arthurmco-github-io-blog"

[params]
  fullWidthTheme = false
  centerTheme = true
  themeColor = "red"
  enableGitInfo = true
  showLastUpdated = true
  readingTime = true
  updatedDatePrefix = "Modificado em"

  [params.logo]
    logoText = "Blog do Arthur M."

[languages]
  [languages.en]
    title = "Blog do Arthur M."
    subtitle = "Meu diário de coisas interessantes"

  [languages.pt-br]
    title = "Blog do Arthur M."
    subtitle = "Meu diário de coisas interessantes"


[taxonomies]
archive = 'archive'
tags = 'tags'
keywords = 'keywords'